const { GoogleGenerativeAI } = require("@google/generative-ai");
const { sendEmail } = require('./config/emailService');
const Event = require('./models/Event');
const Sentiment = require('./models/Sentiment');
require('dotenv').config();

// Gemini AI Init
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "models/gemini-1.5-flash-latest" });

// ✅ Safe date utility
function safeDate(input) {
  const d = new Date(input);
  return isNaN(d.getTime()) ? null : d.toISOString();
}

async function generateAndSendReport(toEmail) {
  try {
    // Get recent data
    const events = await Event.find().sort({ timestamp: -1 }).limit(50).lean();
    const sentiments = await Sentiment.find().sort({ timestamp: -1 }).limit(30).lean();

    // Filter + sanitize
    const safeEvents = events
      .map(e => ({
        eventType: e.eventType,
        timestamp: safeDate(e.timestamp),
        platform: e.browserData?.platform,
        browser: e.browserData?.browser,
        city: e.location?.city,
      }))
      .filter(e => e.timestamp); // ✅ Only valid entries

    const safeSentiments = sentiments
      .map(s => ({
        sentiment: s.sentiment,
        score: s.score,
        timestamp: safeDate(s.timestamp),
        text: typeof s.text === 'string' ? s.text.slice(0, 100) : '',
      }))
      .filter(s => s.timestamp); // ✅ Only valid entries

    // Skip if no data
    if (!safeEvents.length && !safeSentiments.length) {
      console.log("⚠️ No valid data for report. Skipping.");
      return;
    }

    // Gemini Prompt
    const prompt = `
Generate a professional weekly analytics report including:
- Overview of user activity
- Sentiment trends
- Platform/browser breakdown
- Summary + recommendation

Data:
Events:
${JSON.stringify(safeEvents, null, 2)}

Sentiments:
${JSON.stringify(safeSentiments, null, 2)}
`;

    let summary = "Report generation failed.";

    try {
      const result = await model.generateContent({
        contents: [{ role: 'user', parts: [{ text: prompt }] }],
      });
      summary = result?.response?.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || summary;
    } catch (apiErr) {
      console.error("❌ Gemini API Error:", apiErr.message);
    }

    // Email Content
    const emailHtml = `
      <div style="font-family: Arial, sans-serif; padding: 24px; color: #111;">
        <h2 style="color:#4f46e5;">📊 EvoBot Weekly Analytics Report</h2>
        <p style="font-size: 14px; color: #555;">Here is the latest report based on recent user activity and sentiment analysis.</p>
        <hr style="margin: 1em 0;">
        <pre style="white-space: pre-wrap; font-size: 13px;">${summary}</pre>
        <hr style="margin: 1em 0;">
        <p style="font-size: 12px; color: #888;">This report was automatically generated by EvoBot using Gemini AI.</p>
      </div>
    `;

    // Email Send
    await sendEmail(toEmail, '📈 Weekly EvoBot Analytics Report', emailHtml);
    console.log("✅ Report sent to", toEmail);

  } catch (error) {
    console.error("❌ Failed to generate and send report:", error.message);
  }
}

module.exports = generateAndSendReport;
